"""added todos relation

Revision ID: 216dd451a0d5
Revises: 610ec033abc4
Create Date: 2026-03-18 23:08:00.552791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216dd451a0d5'
down_revision: Union[str, Sequence[str], None] = '610ec033abc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_todo_owner_id_users', 'todo', 'users', ['owner_id'], ['id'])

    # Backfill existing todos using any existing user so migration can proceed on non-empty tables.
    conn = op.get_bind()
    fallback_owner_id = conn.execute(sa.text("SELECT id FROM users LIMIT 1")).scalar()
    if fallback_owner_id is not None:
        conn.execute(
            sa.text("UPDATE todo SET owner_id = :owner_id WHERE owner_id IS NULL"),
            {"owner_id": fallback_owner_id},
        )

    remaining_nulls = conn.execute(
        sa.text("SELECT COUNT(*) FROM todo WHERE owner_id IS NULL")
    ).scalar_one()

    # Enforce NOT NULL only when all rows are backfilled.
    if remaining_nulls == 0:
        op.alter_column('todo', 'owner_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_todo_owner_id_users', 'todo', type_='foreignkey')
    op.drop_column('todo', 'owner_id')
    # ### end Alembic commands ###
