"""property and favorites

Revision ID: a94bf176c353
Revises: 216dd451a0d5
Create Date: 2026-04-01 09:54:05.012443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a94bf176c353'
down_revision: Union[str, Sequence[str], None] = '216dd451a0d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('available', 'sold', name='property_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('bathrooms >= 0', name='ck_properties_bathrooms_positive'),
    sa.CheckConstraint('bedrooms >= 0', name='ck_properties_bedrooms_positive'),
    sa.CheckConstraint('price >= 0', name='ck_properties_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_properties_state', 'properties', ['state'], unique=False)
    op.create_index('ix_properties_status', 'properties', ['status'], unique=False)
    op.create_table('favourites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_favourites_user_property')
    )
    op.create_index('ix_favourites_property_id', 'favourites', ['property_id'], unique=False)
    op.create_index('ix_favourites_user_id', 'favourites', ['user_id'], unique=False)
    op.drop_index(op.f('ix_todo_user_id'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('todo_pkey'))
    )
    op.create_index(op.f('ix_todo_user_id'), 'todo', ['user_id'], unique=False)
    op.drop_index('ix_favourites_user_id', table_name='favourites')
    op.drop_index('ix_favourites_property_id', table_name='favourites')
    op.drop_table('favourites')
    op.drop_index('ix_properties_status', table_name='properties')
    op.drop_index('ix_properties_state', table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
